[uetrack_base] # <tracker-name>
label = uetrack_base
protocol = traxpython
command =  uetrack_base
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
# change to your path
paths = /media/kb/2A57A961A1CAB688/kb/2080/uetrack/lib/test/vot

[uetrack_small] # <tracker-name>
label = uetrack_small
protocol = traxpython
command =  uetrack_small
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
# change to your path
paths = /media/kb/2A57A961A1CAB688/kb/2080/uetrack/lib/test/vot


[uetrack_tiny] # <tracker-name>
label = uetrack_tiny
protocol = traxpython
command =  uetrack_tiny
# Specify a path to trax python wrapper if it is not visible (separate by ; if using multiple paths)
# change to your path
paths = /media/kb/2A57A961A1CAB688/kb/2080/uetrack/lib/test/vot
